//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMProductos {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Datoos : global::System.Configuration.ApplicationSettingsBase {
        
        private static Datoos defaultInstance = ((Datoos)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Datoos())));
        
        public static Datoos Default {
            get {
                return defaultInstance;
            }
        }
    }
}
